name: Pitch
description: 'Do you have an idea and a product enhancement? Time to pitch!'
title: '[PITCH]:'
labels: ['Pitch']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this pitch, there are some pitch examples ([1](https://github.com/orgs/asyncapi/projects/16?pane=issue&itemId=24119991), [2](https://github.com/orgs/asyncapi/projects/16?pane=issue&itemId=29776963))
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: "What's the story exposing the problem the users are facing"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: "Proposed solution (e.g., examples, mockups, views...)"
    validations:
      required: true
  - type: textarea
    id: rabbit_holes
    attributes:
      label: Rabbit holes
      description: "Potential technical, design... challenges"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: "Describe a list of tasks or issues that need to be done (you don't need to have an exhaustive list of all the tasks in the beginning)"
      placholder: | 
        - [ ] Task
    validations:
      required: true
  - type: textarea
    id: out-of-bounds
    attributes:
      label: Out of bounds
      description: "What won't be part of the scope"
    validations:
      required: true
  - type: textarea
    id: success
    attributes:
      label: Success criteria
      description: "How do we know that this will be a success?"
    validations:
      required: true
