name: Issue Parser


on:
  issues:
    types:
      - edited
      - opened

jobs:
  parse_issue:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - name: Parse Issue Description
        id: parse
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            const regexSimple = /(Bet\s+(\S+)?#(\d+))/;
            const description = context.payload.issue.body;
            const match = regexSimple.exec(description);
            // Simple cases Bet #[number] and Bet User/Repo#[number]
            if (match) {
              const repoFull = match[2] ? match[2] : context.payload.repository.full_name;
              const user = repoFull.split('/')[0]
              conset repo = repoFull.split('/')[1]
              const issueNumber = match[3];
              const repoUrl = `https://github.com/${repoFull}`;
              

              return {
                issueNumber: issueNumber,
                user: user,
                repo: repo,
                repoUrl: repoUrl
              };
            } else {
              // Case 3: Bet https://github.com/user/repo/issues/[number]
              const regexUrl = /(Bet\s+?https:\/\/github\.com\/([^\/]+)\/([^\/]+)\/issues\/(\d+))/
              const match = regexSimple.exec(description);
              if (match) {
                const issueNumber = match[4];
                const user =  match[2]
                conset repo = match[3]
                const repoUrl = `https://github.com/${user}/${repo}`;

                return {
                  issueNumber: issueNumber,
                  user: user,
                  repo: repo,
                  repoUrl: repoUrl
              };
            }

      - name: Output Issue Number and Repo URL
        id: output
        uses: actions/github-script@v6
        with:
          script: |
            const res = ${{ steps.parse.outputs.result }}
            if (!res) {
              console.log("No Bet linked to this issue")
              return
            }
            const issueNumber = res.issueNumber
            const repo = res.repoUrl
            console.log(res)
