name: Issue Parser


on:
  issues:
    types:
      - edited
      - opened

jobs:
  parse_issue:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - name: Parse Issue Description
        id: parse
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            const regex = /(Bet\s+(\S+)?#(\d+))/;
            const description = context.payload.issue.body;
            const match = regex.exec(description);
            console.log(match)
            console.log(description)
            if (match) {
              const repo = match[2] ? match[2] : context.payload.repository.full_name;
              const issueNumber = match[3];
              const repoUrl = `https://github.com/${repo}`;

              return {
                issueNumber: issueNumber,
                repoUrl: repoUrl
              };
            } else {
              return null;
            }

      - name: Output Issue Number and Repo URL
        id: output
        uses: actions/github-script@v6
        with:
          script: |
            const res = ${{ steps.parse.outputs.result }}
            if (!res) {
              console.log("No Bet linked to this issue")
              return
            }
            const issueNumber = res.issueNumber
            const repo = res.repoUrl
            console.log(res)
