name: PR Validation Workflow

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR label and title
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.pull_request.title;
            const labels = context.payload.pull_request.labels;
            const hasAdrLabel = labels.some(label => label.name === 'kind/adr');
            const startsWithAdr = /^\[ADR-\d{4}\]/.test(title);
            console.log(`title : ${title} - labels: ${labels} - hasAdrLabel: ${hasAdrLabel} - startsWithAdr: ${startsWithAdr}`);
            