name: Flag issues as scopes

on:
  issues:
    types:
      - edited
  workflow_dispatch: {}

jobs:
  flag-issues-as-scopes:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - name: Extract scope tasks
        id: extract-tasks
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const changes = context.payload.changes;
            const issueNumber = issue.number;
            const projectId = 4; // Replace with the desired project number
            const kind = 'kind/bet'; // Replace with the desired kind

            const isIssueBelongsToProject = issue.project_card !== undefined && issue.project_card.project_id === projectId;
            const isIssueKindBet = issue.labels.some(label => label.name === kind);
            console.log(`Issue Chages`, changes.body, `Current body`, issue.body);
            console.log(`isIssueBelongsToProject`, isIssueBelongsToProject, `isIssueKindBet`, isIssueKindBet)
            if (isIssueKindBet) {
              const oldDescription = changes.body ? changes.body.from : '';
              const newDescription = issue.body;

              if (oldDescription !== newDescription) {
                console.log('Issue description has changed.');
                console.log('Old Description:', oldDescription);
                console.log('New Description:', newDescription);

                const scopeIndex = newDescription.indexOf('### Scope');
                if (scopeIndex !== -1) {
                  const scopeText = newDescription.slice(scopeIndex);
                  const pattern = /### Scope\s*\n([\s\S]*?)(?=###|$)/
                  const match = scopeText.match(pattern);
                  const tasks = match[1].trim().split('\n');
                  // echo "tasks=$tasks" >> $GITHUB_OUTPUT
                  if (tasks && tasks.length > 0) {
                    console.log('Tasks:');
                    console.log(JSON.stringify(tasks));
                  } else {
                    console.log('No tasks found under the Scope section.');
                  }
                } else {
                  console.log('Scope section not found in the description.');
                }
              } else {
                console.log('Issue description did not change.');
              }
            }
      - name: Add to project
        id: add-project
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log("nothing")

